name: 'Deploy :edge on Schedule'

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 5

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build-images:
    name: 'Build Images'
    uses: ./.github/workflows/generic_build.yml
    with:
      platforms: linux/amd64,linux/arm64

  scan-image:
    name: 'Scan Image for Vulnerabilities'
    needs: build-images
    uses: ./.github/workflows/generic_vulnerability-scan.yml
    with:
      cache-key: ${{ needs.build-images.outputs.build-cache-key }}

  publish-images:
    name: 'Publish Images'
    needs: build-images
    uses: ./.github/workflows/generic_publish.yml
    with:
      cache-key: ${{ needs.build-images.outputs.build-cache-key }}
    secrets: inherit
